image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

stages:
  - test

test:
  stage: test
  script:
    - npm install
    - npm audit
    - npm test

